@startuml

skinparam shadowing false
scale 2

title: Overview Platform (WIP)\njoinus4health.eu
header version: %date("dd.MM.yyyy")

skinparam actorStyle awesome
skinparam nodeBackgroundColor<<Server>> #ffccaa
skinparam rectangleBackgroundColor<<Partner>> #cccccc
skinparam rectangleBackgroundColor<<Provider>> #ddbbaa
skinparam componentBackgroundColor #fefece
skinparam databaseBackgroundColor #fefece

legend
**Legend**
- DPA "Data Processing Agreement" - Auftragsverarbeitungsvertrag (AVV)
end legend

!define DPA(_name)   note "DPA" as _name #aaaaff

actor "User" as user

rectangle "UMG\ncoordinator" as umg #ffcccc {
    rectangle "ICM SHIP-KEF" {
        actor "SHIP-IT" as ship
        actor "JoinUs4Health\nProject Manage-\nment Team" as umg_team
    }
}

rectangle "science4people.eu" <<Partner>> as s4p {
    DPA(dpa_s4p)
    actor "science4people\nPartner" as s4p_partner
}

cloud "Internet" {
    rectangle "netcup" <<Provider>> as netcup {
        DPA(dpa_netcup)
        node "Managed Private Server" <<Server>> as mps {
            node "Platform-Server" <<Server>> as platform_server {
                component "WordPress" <<Web-Framework>> as wp {
                    component "bbPress"
                    component "BuddyPress*"
                    component "TaskBreaker"
                    component "own Development"
                }
                folder "WordPress-Files" as wpfolder
                database "DBMS MariaDB" as dbms {
                    database "platform data" <<database>> as db_plattform
                    database "user data" <<database>> as db_user
                }
                wp --> dbms     #black
                wp --> wpfolder #black
            }
'            node "Questionnaire-Server" <<Server>> as lime_server {
'                component "LimeSurvey" <<Web-Framework>> as lime
'                database "MariaDB" <<database>> as lime_db
'                
'                lime    -->     lime_db #black
'            }
'            
'            wp      =(0=    lime    #00aa00
        }
    }
    rectangle "werk21" <<Provider>> as bbb_provider {
        DPA(dpa_bbb)
        node "Conference-Server" <<Server>> as bbb_server {
            component "BigBlueButton" <<Web-Framework>> as bbb
            
        }
    }
    wp     =(0=     bbb #00aa00

    interface "Conference" as i_bbb
    interface "Platform" as i_web
'    interface "Questionnaire" as i_lime

    i_web   .u.     wp
'    i_lime  .u.     lime
    i_bbb   .u.     bbb

    node "deepl.com" as deepl #ddbbaa {
        DPA(dpa_deepl)
        component "Translator" as deepl_trans
    }
    wp     =(0==     deepl_trans #00aa00
}

ship        -->     mps         : Adminis-\ntration
ship        -->     bbb_server  : Adminis-\ntration
ship        -->     deepl       : Adminis-\ntration
s4p_partner -->     wp          : Adminis-\ntration
's4p_partner -->     lime        : Adminis-\ntration

i_web   -[hidden]-  i_bbb
'i_bbb   -[hidden]-  i_lime

user    --> i_web
user    --> i_bbb
'user    -u->  i_lime

@enduml
