@startuml

skinparam shadowing false
scale 2

title: Overview Homepage\njoinus4health.eu
header version: %date("dd.MM.yyyy")

skinparam actorStyle awesome
skinparam rectangleBackgroundColor<<Partner>> #cccccc
skinparam componentBackgroundColor #fefece

legend
**Legend**
- DPA "Data Processing Agreement" - Auftragsverarbeitungsvertrag (AVV)
end legend

!define DPA(_name)   note "DPA" as _name #aaaaff

actor "User" as user

rectangle "UMG\ncoordinator" as umg #ffcccc {
    rectangle "ICM SHIP-KEF" {
        actor "SHIP-IT" as ship
        actor "JoinUs4Health\nProject Manage-\nment Team" as umg_team
    }
}

rectangle "Website Editors" <<Partner>> as editors {
    DPA(dpa_editors)
    actor "Project Partners\nwith editing-rights only" as editor_partner
}

rectangle "science4people.eu" <<Partner>> as s4p {
    DPA(dpa_s4p)
    actor "science4people\nPartner" as s4p_partner
}

rectangle "Medical University\nof Bialystok" <<Partner>> as bi {
    DPA(dpa_bia)
    actor "Bialystok\nPartner" as bi_partner
}

rectangle "Medical Center of the\nErasmus University Rotterdamm" <<Partner>> as erasmus {
    DPA(dpa_era)
    actor "Erasmus\nPartner" as erasmus_partner
}

cloud "Internet" {
    node "netcup.de" <<Provider>> as netcup #ddbbaa {
        DPA(dpa_netcup)
        rectangle "Domain joinus4health.eu" as webspace #ffccaa {
            component "WordPress" <<Web-Framework>> as wp {
                component "Elementor"
                component "TranslatePress"
                component "Yoast SEO"
                component "One Click Accessibility"
            }
            rectangle "//separate Server//" {
                database "MariaDB" <<database>> as my
            }
            folder "WordPress-Files" as wpfolder
            file "log files" as log
            component "Webalizer" <<statistic-tool>> as stats
            component "E-Mail" as email {
                rectangle "de/en" <<inbox>> as e_de
                rectangle "pl/en" <<inbox>> as e_pl
                rectangle "nl/en" <<inbox>> as e_nl
            }
            wp --> my           #black
            wp -l-> wpfolder    #black
            stats --> log       #black
        }
        interface "Homepage" as i_web
        interface "E-Mail" as i_mail
        i_web .u. wp
        i_mail .u. email
    }
    node "deepl.com" as deepl #ddbbaa {
        DPA(dpa_deepl)
        component "Translator" as deepl_trans
    }
    wp     =(0==     deepl_trans #00aa00
}

umg -[hidden]-  editors
umg -[hidden]-  s4p
umg -[hidden]-  bi
umg -[hidden]-  erasmus

ship            -->     webspace    : Adminis-\ntration
s4p_partner     -->     wp          : Adminis-\ntration
editor_partner  -->     wp          : Content-\nediting

umg_team        --> e_de
bi_partner      --> e_pl
erasmus_partner --> e_nl

user    -u-> i_web      : use
user    -u-> i_mail     : send

@enduml
